<?php
/**
 * MyDriversApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * MyDriversApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MyDriversApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'myDriversDraftsGet' => [
            'application/json',
        ],
        'myDriversDraftsPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation myDriversDraftsGet
     *
     * Retrieve all My Drivers draft orders
     *
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  \DateTime $from The start date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  \DateTime $to The end date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DraftOrdersGet200Response
     */
    public function myDriversDraftsGet($x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, $from = null, $to = null, string $contentType = self::contentTypes['myDriversDraftsGet'][0])
    {
        list($response) = $this->myDriversDraftsGetWithHttpInfo($x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $from, $to, $contentType);
        return $response;
    }

    /**
     * Operation myDriversDraftsGetWithHttpInfo
     *
     * Retrieve all My Drivers draft orders
     *
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  \DateTime $from The start date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  \DateTime $to The end date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DraftOrdersGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function myDriversDraftsGetWithHttpInfo($x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, $from = null, $to = null, string $contentType = self::contentTypes['myDriversDraftsGet'][0])
    {
        $request = $this->myDriversDraftsGetRequest($x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $from, $to, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\DraftOrdersGet200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\DraftOrdersGet200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\DraftOrdersGet200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\DraftOrdersGet200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\DraftOrdersGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation myDriversDraftsGetAsync
     *
     * Retrieve all My Drivers draft orders
     *
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  \DateTime $from The start date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  \DateTime $to The end date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function myDriversDraftsGetAsync($x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, $from = null, $to = null, string $contentType = self::contentTypes['myDriversDraftsGet'][0])
    {
        return $this->myDriversDraftsGetAsyncWithHttpInfo($x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $from, $to, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation myDriversDraftsGetAsyncWithHttpInfo
     *
     * Retrieve all My Drivers draft orders
     *
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  \DateTime $from The start date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  \DateTime $to The end date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function myDriversDraftsGetAsyncWithHttpInfo($x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, $from = null, $to = null, string $contentType = self::contentTypes['myDriversDraftsGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\DraftOrdersGet200Response';
        $request = $this->myDriversDraftsGetRequest($x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $from, $to, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'myDriversDraftsGet'
     *
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  \DateTime $from The start date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  \DateTime $to The end date to query (YYYY-MM-DD). Default is today. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function myDriversDraftsGetRequest($x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, $from = null, $to = null, string $contentType = self::contentTypes['myDriversDraftsGet'][0])
    {







        $resourcePath = '/myDrivers/drafts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_evermile_merchant_id !== null) {
            $headerParams['X-EVERMILE-MERCHANT-ID'] = ObjectSerializer::toHeaderValue($x_evermile_merchant_id);
        }
        // header params
        if ($x_evermile_trace_id !== null) {
            $headerParams['X-EVERMILE-TRACE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_trace_id);
        }
        // header params
        if ($x_evermile_store_id !== null) {
            $headerParams['X-EVERMILE-STORE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_store_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation myDriversDraftsPost
     *
     * Save a My Drivers draft order
     *
     * @param  \OpenAPI\Client\Model\MyDriversDraftsPostRequest $my_drivers_drafts_post_request my_drivers_drafts_post_request (required)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner
     */
    public function myDriversDraftsPost($my_drivers_drafts_post_request, $x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, string $contentType = self::contentTypes['myDriversDraftsPost'][0])
    {
        list($response) = $this->myDriversDraftsPostWithHttpInfo($my_drivers_drafts_post_request, $x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $contentType);
        return $response;
    }

    /**
     * Operation myDriversDraftsPostWithHttpInfo
     *
     * Save a My Drivers draft order
     *
     * @param  \OpenAPI\Client\Model\MyDriversDraftsPostRequest $my_drivers_drafts_post_request (required)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner, HTTP status code, HTTP response headers (array of strings)
     */
    public function myDriversDraftsPostWithHttpInfo($my_drivers_drafts_post_request, $x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, string $contentType = self::contentTypes['myDriversDraftsPost'][0])
    {
        $request = $this->myDriversDraftsPostRequest($my_drivers_drafts_post_request, $x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation myDriversDraftsPostAsync
     *
     * Save a My Drivers draft order
     *
     * @param  \OpenAPI\Client\Model\MyDriversDraftsPostRequest $my_drivers_drafts_post_request (required)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function myDriversDraftsPostAsync($my_drivers_drafts_post_request, $x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, string $contentType = self::contentTypes['myDriversDraftsPost'][0])
    {
        return $this->myDriversDraftsPostAsyncWithHttpInfo($my_drivers_drafts_post_request, $x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation myDriversDraftsPostAsyncWithHttpInfo
     *
     * Save a My Drivers draft order
     *
     * @param  \OpenAPI\Client\Model\MyDriversDraftsPostRequest $my_drivers_drafts_post_request (required)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function myDriversDraftsPostAsyncWithHttpInfo($my_drivers_drafts_post_request, $x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, string $contentType = self::contentTypes['myDriversDraftsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\DraftOrdersGet200ResponseDraftsInner';
        $request = $this->myDriversDraftsPostRequest($my_drivers_drafts_post_request, $x_evermile_merchant_id, $x_evermile_trace_id, $x_evermile_store_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'myDriversDraftsPost'
     *
     * @param  \OpenAPI\Client\Model\MyDriversDraftsPostRequest $my_drivers_drafts_post_request (required)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_store_id A store ID for an order&#39;s store platform context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['myDriversDraftsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function myDriversDraftsPostRequest($my_drivers_drafts_post_request, $x_evermile_merchant_id = null, $x_evermile_trace_id = null, $x_evermile_store_id = null, string $contentType = self::contentTypes['myDriversDraftsPost'][0])
    {

        // verify the required parameter 'my_drivers_drafts_post_request' is set
        if ($my_drivers_drafts_post_request === null || (is_array($my_drivers_drafts_post_request) && count($my_drivers_drafts_post_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $my_drivers_drafts_post_request when calling myDriversDraftsPost'
            );
        }





        $resourcePath = '/myDrivers/drafts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_evermile_merchant_id !== null) {
            $headerParams['X-EVERMILE-MERCHANT-ID'] = ObjectSerializer::toHeaderValue($x_evermile_merchant_id);
        }
        // header params
        if ($x_evermile_trace_id !== null) {
            $headerParams['X-EVERMILE-TRACE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_trace_id);
        }
        // header params
        if ($x_evermile_store_id !== null) {
            $headerParams['X-EVERMILE-STORE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_store_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($my_drivers_drafts_post_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($my_drivers_drafts_post_request));
            } else {
                $httpBody = $my_drivers_drafts_post_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
