<?php
/**
 * ValidationsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ValidationsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ValidationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addressValidateGet' => [
            'application/json',
        ],
        'emailValidateGet' => [
            'application/json',
        ],
        'phoneValidateGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addressValidateGet
     *
     * Validate address
     *
     * @param  string $street The street for delivery (required)
     * @param  string $city The city for delivery (required)
     * @param  string $postcode The postal code for delivery (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $country 2-letter code for the country for delivery (optional)
     * @param  string $coordinates The (lat, lng) coordinates. Not required, but will be used if provided. (optional)
     * @param  bool $allow_nationwide Whether to allow nationwide search (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addressValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function addressValidateGet($street, $city, $postcode, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, $country = null, $coordinates = null, $allow_nationwide = null, string $contentType = self::contentTypes['addressValidateGet'][0])
    {
        $this->addressValidateGetWithHttpInfo($street, $city, $postcode, $x_evermile_trace_id, $x_evermile_merchant_id, $country, $coordinates, $allow_nationwide, $contentType);
    }

    /**
     * Operation addressValidateGetWithHttpInfo
     *
     * Validate address
     *
     * @param  string $street The street for delivery (required)
     * @param  string $city The city for delivery (required)
     * @param  string $postcode The postal code for delivery (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $country 2-letter code for the country for delivery (optional)
     * @param  string $coordinates The (lat, lng) coordinates. Not required, but will be used if provided. (optional)
     * @param  bool $allow_nationwide Whether to allow nationwide search (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addressValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addressValidateGetWithHttpInfo($street, $city, $postcode, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, $country = null, $coordinates = null, $allow_nationwide = null, string $contentType = self::contentTypes['addressValidateGet'][0])
    {
        $request = $this->addressValidateGetRequest($street, $city, $postcode, $x_evermile_trace_id, $x_evermile_merchant_id, $country, $coordinates, $allow_nationwide, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation addressValidateGetAsync
     *
     * Validate address
     *
     * @param  string $street The street for delivery (required)
     * @param  string $city The city for delivery (required)
     * @param  string $postcode The postal code for delivery (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $country 2-letter code for the country for delivery (optional)
     * @param  string $coordinates The (lat, lng) coordinates. Not required, but will be used if provided. (optional)
     * @param  bool $allow_nationwide Whether to allow nationwide search (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addressValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addressValidateGetAsync($street, $city, $postcode, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, $country = null, $coordinates = null, $allow_nationwide = null, string $contentType = self::contentTypes['addressValidateGet'][0])
    {
        return $this->addressValidateGetAsyncWithHttpInfo($street, $city, $postcode, $x_evermile_trace_id, $x_evermile_merchant_id, $country, $coordinates, $allow_nationwide, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addressValidateGetAsyncWithHttpInfo
     *
     * Validate address
     *
     * @param  string $street The street for delivery (required)
     * @param  string $city The city for delivery (required)
     * @param  string $postcode The postal code for delivery (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $country 2-letter code for the country for delivery (optional)
     * @param  string $coordinates The (lat, lng) coordinates. Not required, but will be used if provided. (optional)
     * @param  bool $allow_nationwide Whether to allow nationwide search (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addressValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addressValidateGetAsyncWithHttpInfo($street, $city, $postcode, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, $country = null, $coordinates = null, $allow_nationwide = null, string $contentType = self::contentTypes['addressValidateGet'][0])
    {
        $returnType = '';
        $request = $this->addressValidateGetRequest($street, $city, $postcode, $x_evermile_trace_id, $x_evermile_merchant_id, $country, $coordinates, $allow_nationwide, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addressValidateGet'
     *
     * @param  string $street The street for delivery (required)
     * @param  string $city The city for delivery (required)
     * @param  string $postcode The postal code for delivery (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $country 2-letter code for the country for delivery (optional)
     * @param  string $coordinates The (lat, lng) coordinates. Not required, but will be used if provided. (optional)
     * @param  bool $allow_nationwide Whether to allow nationwide search (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addressValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addressValidateGetRequest($street, $city, $postcode, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, $country = null, $coordinates = null, $allow_nationwide = null, string $contentType = self::contentTypes['addressValidateGet'][0])
    {

        // verify the required parameter 'street' is set
        if ($street === null || (is_array($street) && count($street) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $street when calling addressValidateGet'
            );
        }

        // verify the required parameter 'city' is set
        if ($city === null || (is_array($city) && count($city) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $city when calling addressValidateGet'
            );
        }

        // verify the required parameter 'postcode' is set
        if ($postcode === null || (is_array($postcode) && count($postcode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $postcode when calling addressValidateGet'
            );
        }







        $resourcePath = '/address/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $street,
            'street', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $city,
            'city', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country,
            'country', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $postcode,
            'postcode', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $coordinates,
            'coordinates', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $allow_nationwide,
            'allowNationwide', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_evermile_trace_id !== null) {
            $headerParams['X-EVERMILE-TRACE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_trace_id);
        }
        // header params
        if ($x_evermile_merchant_id !== null) {
            $headerParams['X-EVERMILE-MERCHANT-ID'] = ObjectSerializer::toHeaderValue($x_evermile_merchant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation emailValidateGet
     *
     * Validate email
     *
     * @param  string $email The email to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['emailValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function emailValidateGet($email, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['emailValidateGet'][0])
    {
        $this->emailValidateGetWithHttpInfo($email, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);
    }

    /**
     * Operation emailValidateGetWithHttpInfo
     *
     * Validate email
     *
     * @param  string $email The email to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['emailValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function emailValidateGetWithHttpInfo($email, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['emailValidateGet'][0])
    {
        $request = $this->emailValidateGetRequest($email, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation emailValidateGetAsync
     *
     * Validate email
     *
     * @param  string $email The email to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['emailValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function emailValidateGetAsync($email, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['emailValidateGet'][0])
    {
        return $this->emailValidateGetAsyncWithHttpInfo($email, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation emailValidateGetAsyncWithHttpInfo
     *
     * Validate email
     *
     * @param  string $email The email to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['emailValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function emailValidateGetAsyncWithHttpInfo($email, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['emailValidateGet'][0])
    {
        $returnType = '';
        $request = $this->emailValidateGetRequest($email, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'emailValidateGet'
     *
     * @param  string $email The email to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['emailValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function emailValidateGetRequest($email, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['emailValidateGet'][0])
    {

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling emailValidateGet'
            );
        }




        $resourcePath = '/email/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $email,
            'email', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($x_evermile_trace_id !== null) {
            $headerParams['X-EVERMILE-TRACE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_trace_id);
        }
        // header params
        if ($x_evermile_merchant_id !== null) {
            $headerParams['X-EVERMILE-MERCHANT-ID'] = ObjectSerializer::toHeaderValue($x_evermile_merchant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation phoneValidateGet
     *
     * Validate phone number
     *
     * @param  string $phone The phone number to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['phoneValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function phoneValidateGet($phone, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['phoneValidateGet'][0])
    {
        $this->phoneValidateGetWithHttpInfo($phone, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);
    }

    /**
     * Operation phoneValidateGetWithHttpInfo
     *
     * Validate phone number
     *
     * @param  string $phone The phone number to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['phoneValidateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function phoneValidateGetWithHttpInfo($phone, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['phoneValidateGet'][0])
    {
        $request = $this->phoneValidateGetRequest($phone, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation phoneValidateGetAsync
     *
     * Validate phone number
     *
     * @param  string $phone The phone number to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['phoneValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function phoneValidateGetAsync($phone, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['phoneValidateGet'][0])
    {
        return $this->phoneValidateGetAsyncWithHttpInfo($phone, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation phoneValidateGetAsyncWithHttpInfo
     *
     * Validate phone number
     *
     * @param  string $phone The phone number to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['phoneValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function phoneValidateGetAsyncWithHttpInfo($phone, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['phoneValidateGet'][0])
    {
        $returnType = '';
        $request = $this->phoneValidateGetRequest($phone, $x_evermile_trace_id, $x_evermile_merchant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'phoneValidateGet'
     *
     * @param  string $phone The phone number to validate (required)
     * @param  string $x_evermile_trace_id A trace ID for tracing the request through the Evermile platform (optional)
     * @param  string $x_evermile_merchant_id The merchant ID, if using a client credentials token. Will be ignored with a regular user token. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['phoneValidateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function phoneValidateGetRequest($phone, $x_evermile_trace_id = null, $x_evermile_merchant_id = null, string $contentType = self::contentTypes['phoneValidateGet'][0])
    {

        // verify the required parameter 'phone' is set
        if ($phone === null || (is_array($phone) && count($phone) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $phone when calling phoneValidateGet'
            );
        }




        $resourcePath = '/phone/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $phone,
            'phone', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($x_evermile_trace_id !== null) {
            $headerParams['X-EVERMILE-TRACE-ID'] = ObjectSerializer::toHeaderValue($x_evermile_trace_id);
        }
        // header params
        if ($x_evermile_merchant_id !== null) {
            $headerParams['X-EVERMILE-MERCHANT-ID'] = ObjectSerializer::toHeaderValue($x_evermile_merchant_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
