<?php
/**
 * LocationPutRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LocationPutRequest Class Doc Comment
 *
 * @category Class
 * @description A request to update or create a location
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LocationPutRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_location_put_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'location' => '\OpenAPI\Client\Model\LocationPutRequestLocation',
        'apply_delivery_hours_to_all' => 'bool',
        'apply_store_pickup_hours_to_all' => 'bool',
        'apply_delivery_preparation_times_to_all' => 'bool',
        'apply_store_pickup_preparation_times_to_all' => 'bool',
        'apply_preparation_times_to_all' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'location' => null,
        'apply_delivery_hours_to_all' => null,
        'apply_store_pickup_hours_to_all' => null,
        'apply_delivery_preparation_times_to_all' => null,
        'apply_store_pickup_preparation_times_to_all' => null,
        'apply_preparation_times_to_all' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'location' => false,
        'apply_delivery_hours_to_all' => false,
        'apply_store_pickup_hours_to_all' => false,
        'apply_delivery_preparation_times_to_all' => false,
        'apply_store_pickup_preparation_times_to_all' => false,
        'apply_preparation_times_to_all' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'location' => 'location',
        'apply_delivery_hours_to_all' => 'applyDeliveryHoursToAll',
        'apply_store_pickup_hours_to_all' => 'applyStorePickupHoursToAll',
        'apply_delivery_preparation_times_to_all' => 'applyDeliveryPreparationTimesToAll',
        'apply_store_pickup_preparation_times_to_all' => 'applyStorePickupPreparationTimesToAll',
        'apply_preparation_times_to_all' => 'applyPreparationTimesToAll'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'location' => 'setLocation',
        'apply_delivery_hours_to_all' => 'setApplyDeliveryHoursToAll',
        'apply_store_pickup_hours_to_all' => 'setApplyStorePickupHoursToAll',
        'apply_delivery_preparation_times_to_all' => 'setApplyDeliveryPreparationTimesToAll',
        'apply_store_pickup_preparation_times_to_all' => 'setApplyStorePickupPreparationTimesToAll',
        'apply_preparation_times_to_all' => 'setApplyPreparationTimesToAll'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'location' => 'getLocation',
        'apply_delivery_hours_to_all' => 'getApplyDeliveryHoursToAll',
        'apply_store_pickup_hours_to_all' => 'getApplyStorePickupHoursToAll',
        'apply_delivery_preparation_times_to_all' => 'getApplyDeliveryPreparationTimesToAll',
        'apply_store_pickup_preparation_times_to_all' => 'getApplyStorePickupPreparationTimesToAll',
        'apply_preparation_times_to_all' => 'getApplyPreparationTimesToAll'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('apply_delivery_hours_to_all', $data ?? [], null);
        $this->setIfExists('apply_store_pickup_hours_to_all', $data ?? [], null);
        $this->setIfExists('apply_delivery_preparation_times_to_all', $data ?? [], null);
        $this->setIfExists('apply_store_pickup_preparation_times_to_all', $data ?? [], null);
        $this->setIfExists('apply_preparation_times_to_all', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['location'] === null) {
            $invalidProperties[] = "'location' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\LocationPutRequestLocation
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\LocationPutRequestLocation $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets apply_delivery_hours_to_all
     *
     * @return bool|null
     */
    public function getApplyDeliveryHoursToAll()
    {
        return $this->container['apply_delivery_hours_to_all'];
    }

    /**
     * Sets apply_delivery_hours_to_all
     *
     * @param bool|null $apply_delivery_hours_to_all Whether to apply the delivery collection hours to all locations
     *
     * @return self
     */
    public function setApplyDeliveryHoursToAll($apply_delivery_hours_to_all)
    {
        if (is_null($apply_delivery_hours_to_all)) {
            throw new \InvalidArgumentException('non-nullable apply_delivery_hours_to_all cannot be null');
        }
        $this->container['apply_delivery_hours_to_all'] = $apply_delivery_hours_to_all;

        return $this;
    }

    /**
     * Gets apply_store_pickup_hours_to_all
     *
     * @return bool|null
     */
    public function getApplyStorePickupHoursToAll()
    {
        return $this->container['apply_store_pickup_hours_to_all'];
    }

    /**
     * Sets apply_store_pickup_hours_to_all
     *
     * @param bool|null $apply_store_pickup_hours_to_all Whether to apply the store pickup hours to all locations
     *
     * @return self
     */
    public function setApplyStorePickupHoursToAll($apply_store_pickup_hours_to_all)
    {
        if (is_null($apply_store_pickup_hours_to_all)) {
            throw new \InvalidArgumentException('non-nullable apply_store_pickup_hours_to_all cannot be null');
        }
        $this->container['apply_store_pickup_hours_to_all'] = $apply_store_pickup_hours_to_all;

        return $this;
    }

    /**
     * Gets apply_delivery_preparation_times_to_all
     *
     * @return bool|null
     */
    public function getApplyDeliveryPreparationTimesToAll()
    {
        return $this->container['apply_delivery_preparation_times_to_all'];
    }

    /**
     * Sets apply_delivery_preparation_times_to_all
     *
     * @param bool|null $apply_delivery_preparation_times_to_all Whether to apply the preparation times (+ cutoff hour) to all delivery locations
     *
     * @return self
     */
    public function setApplyDeliveryPreparationTimesToAll($apply_delivery_preparation_times_to_all)
    {
        if (is_null($apply_delivery_preparation_times_to_all)) {
            throw new \InvalidArgumentException('non-nullable apply_delivery_preparation_times_to_all cannot be null');
        }
        $this->container['apply_delivery_preparation_times_to_all'] = $apply_delivery_preparation_times_to_all;

        return $this;
    }

    /**
     * Gets apply_store_pickup_preparation_times_to_all
     *
     * @return bool|null
     */
    public function getApplyStorePickupPreparationTimesToAll()
    {
        return $this->container['apply_store_pickup_preparation_times_to_all'];
    }

    /**
     * Sets apply_store_pickup_preparation_times_to_all
     *
     * @param bool|null $apply_store_pickup_preparation_times_to_all Whether to apply the preparation times (+ cutoff hour) to all store pickup locations
     *
     * @return self
     */
    public function setApplyStorePickupPreparationTimesToAll($apply_store_pickup_preparation_times_to_all)
    {
        if (is_null($apply_store_pickup_preparation_times_to_all)) {
            throw new \InvalidArgumentException('non-nullable apply_store_pickup_preparation_times_to_all cannot be null');
        }
        $this->container['apply_store_pickup_preparation_times_to_all'] = $apply_store_pickup_preparation_times_to_all;

        return $this;
    }

    /**
     * Gets apply_preparation_times_to_all
     *
     * @return bool|null
     */
    public function getApplyPreparationTimesToAll()
    {
        return $this->container['apply_preparation_times_to_all'];
    }

    /**
     * Sets apply_preparation_times_to_all
     *
     * @param bool|null $apply_preparation_times_to_all Whether to apply the preparation times (+ cutoff hour) to all locations
     *
     * @return self
     */
    public function setApplyPreparationTimesToAll($apply_preparation_times_to_all)
    {
        if (is_null($apply_preparation_times_to_all)) {
            throw new \InvalidArgumentException('non-nullable apply_preparation_times_to_all cannot be null');
        }
        $this->container['apply_preparation_times_to_all'] = $apply_preparation_times_to_all;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


