<?php
/**
 * QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverage
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverage Class Doc Comment
 *
 * @category Class
 * @description Specific liability coverage info for this proposal
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_quote_post_200_response_dateProposals_inner_proposals_inner_proposal_specificLiabilityCoverage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'max_free_liability_cents' => 'int',
        'max_liability_cents' => 'int',
        'liability_coverage_price_per100_cents' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'max_free_liability_cents' => 'int64',
        'max_liability_cents' => 'int64',
        'liability_coverage_price_per100_cents' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'max_free_liability_cents' => false,
        'max_liability_cents' => false,
        'liability_coverage_price_per100_cents' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'max_free_liability_cents' => 'maxFreeLiabilityCents',
        'max_liability_cents' => 'maxLiabilityCents',
        'liability_coverage_price_per100_cents' => 'liabilityCoveragePricePer100Cents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'max_free_liability_cents' => 'setMaxFreeLiabilityCents',
        'max_liability_cents' => 'setMaxLiabilityCents',
        'liability_coverage_price_per100_cents' => 'setLiabilityCoveragePricePer100Cents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'max_free_liability_cents' => 'getMaxFreeLiabilityCents',
        'max_liability_cents' => 'getMaxLiabilityCents',
        'liability_coverage_price_per100_cents' => 'getLiabilityCoveragePricePer100Cents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('max_free_liability_cents', $data ?? [], null);
        $this->setIfExists('max_liability_cents', $data ?? [], null);
        $this->setIfExists('liability_coverage_price_per100_cents', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['max_free_liability_cents'] === null) {
            $invalidProperties[] = "'max_free_liability_cents' can't be null";
        }
        if ($this->container['max_liability_cents'] === null) {
            $invalidProperties[] = "'max_liability_cents' can't be null";
        }
        if ($this->container['liability_coverage_price_per100_cents'] === null) {
            $invalidProperties[] = "'liability_coverage_price_per100_cents' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets max_free_liability_cents
     *
     * @return int
     */
    public function getMaxFreeLiabilityCents()
    {
        return $this->container['max_free_liability_cents'];
    }

    /**
     * Sets max_free_liability_cents
     *
     * @param int $max_free_liability_cents The maximum amount of free liability coverage for this proposal
     *
     * @return self
     */
    public function setMaxFreeLiabilityCents($max_free_liability_cents)
    {
        if (is_null($max_free_liability_cents)) {
            throw new \InvalidArgumentException('non-nullable max_free_liability_cents cannot be null');
        }
        $this->container['max_free_liability_cents'] = $max_free_liability_cents;

        return $this;
    }

    /**
     * Gets max_liability_cents
     *
     * @return int
     */
    public function getMaxLiabilityCents()
    {
        return $this->container['max_liability_cents'];
    }

    /**
     * Sets max_liability_cents
     *
     * @param int $max_liability_cents The maximum amount of available liability coverage for this proposal
     *
     * @return self
     */
    public function setMaxLiabilityCents($max_liability_cents)
    {
        if (is_null($max_liability_cents)) {
            throw new \InvalidArgumentException('non-nullable max_liability_cents cannot be null');
        }
        $this->container['max_liability_cents'] = $max_liability_cents;

        return $this;
    }

    /**
     * Gets liability_coverage_price_per100_cents
     *
     * @return int
     */
    public function getLiabilityCoveragePricePer100Cents()
    {
        return $this->container['liability_coverage_price_per100_cents'];
    }

    /**
     * Sets liability_coverage_price_per100_cents
     *
     * @param int $liability_coverage_price_per100_cents The maximum amount of available liability coverage for this proposal
     *
     * @return self
     */
    public function setLiabilityCoveragePricePer100Cents($liability_coverage_price_per100_cents)
    {
        if (is_null($liability_coverage_price_per100_cents)) {
            throw new \InvalidArgumentException('non-nullable liability_coverage_price_per100_cents cannot be null');
        }
        $this->container['liability_coverage_price_per100_cents'] = $liability_coverage_price_per100_cents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


