<?php
/**
 * QuoteMultiRoutePost200ResponseProposalsInnerRoutesInnerPickupTasksInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * QuoteMultiRoutePost200ResponseProposalsInnerRoutesInnerPickupTasksInner Class Doc Comment
 *
 * @category Class
 * @description pickup or dropoff task
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class QuoteMultiRoutePost200ResponseProposalsInnerRoutesInnerPickupTasksInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_quote_multiRoute_post_200_response_proposals_inner_routes_inner_pickupTasks_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'location_details' => '\OpenAPI\Client\Model\QuoteMultiRoutePostRequestOriginsInner',
        'estimated_window' => '\OpenAPI\Client\Model\QuotePostRequestDestinationLocationsInnerDeliverySlot',
        'estimated_arrival_time' => '\DateTime',
        'route_order_index' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'location_details' => null,
        'estimated_window' => null,
        'estimated_arrival_time' => 'date-time',
        'route_order_index' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'location_details' => false,
        'estimated_window' => false,
        'estimated_arrival_time' => false,
        'route_order_index' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'location_details' => 'locationDetails',
        'estimated_window' => 'estimatedWindow',
        'estimated_arrival_time' => 'estimatedArrivalTime',
        'route_order_index' => 'routeOrderIndex'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'location_details' => 'setLocationDetails',
        'estimated_window' => 'setEstimatedWindow',
        'estimated_arrival_time' => 'setEstimatedArrivalTime',
        'route_order_index' => 'setRouteOrderIndex'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'location_details' => 'getLocationDetails',
        'estimated_window' => 'getEstimatedWindow',
        'estimated_arrival_time' => 'getEstimatedArrivalTime',
        'route_order_index' => 'getRouteOrderIndex'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('location_details', $data ?? [], null);
        $this->setIfExists('estimated_window', $data ?? [], null);
        $this->setIfExists('estimated_arrival_time', $data ?? [], null);
        $this->setIfExists('route_order_index', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['location_details'] === null) {
            $invalidProperties[] = "'location_details' can't be null";
        }
        if ($this->container['estimated_window'] === null) {
            $invalidProperties[] = "'estimated_window' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The task ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets location_details
     *
     * @return \OpenAPI\Client\Model\QuoteMultiRoutePostRequestOriginsInner
     */
    public function getLocationDetails()
    {
        return $this->container['location_details'];
    }

    /**
     * Sets location_details
     *
     * @param \OpenAPI\Client\Model\QuoteMultiRoutePostRequestOriginsInner $location_details location_details
     *
     * @return self
     */
    public function setLocationDetails($location_details)
    {
        if (is_null($location_details)) {
            throw new \InvalidArgumentException('non-nullable location_details cannot be null');
        }
        $this->container['location_details'] = $location_details;

        return $this;
    }

    /**
     * Gets estimated_window
     *
     * @return \OpenAPI\Client\Model\QuotePostRequestDestinationLocationsInnerDeliverySlot
     */
    public function getEstimatedWindow()
    {
        return $this->container['estimated_window'];
    }

    /**
     * Sets estimated_window
     *
     * @param \OpenAPI\Client\Model\QuotePostRequestDestinationLocationsInnerDeliverySlot $estimated_window estimated_window
     *
     * @return self
     */
    public function setEstimatedWindow($estimated_window)
    {
        if (is_null($estimated_window)) {
            throw new \InvalidArgumentException('non-nullable estimated_window cannot be null');
        }
        $this->container['estimated_window'] = $estimated_window;

        return $this;
    }

    /**
     * Gets estimated_arrival_time
     *
     * @return \DateTime|null
     */
    public function getEstimatedArrivalTime()
    {
        return $this->container['estimated_arrival_time'];
    }

    /**
     * Sets estimated_arrival_time
     *
     * @param \DateTime|null $estimated_arrival_time The estimated arrival time in ISO8601 format
     *
     * @return self
     */
    public function setEstimatedArrivalTime($estimated_arrival_time)
    {
        if (is_null($estimated_arrival_time)) {
            throw new \InvalidArgumentException('non-nullable estimated_arrival_time cannot be null');
        }
        $this->container['estimated_arrival_time'] = $estimated_arrival_time;

        return $this;
    }

    /**
     * Gets route_order_index
     *
     * @return int|null
     */
    public function getRouteOrderIndex()
    {
        return $this->container['route_order_index'];
    }

    /**
     * Sets route_order_index
     *
     * @param int|null $route_order_index The index of the task in the route
     *
     * @return self
     */
    public function setRouteOrderIndex($route_order_index)
    {
        if (is_null($route_order_index)) {
            throw new \InvalidArgumentException('non-nullable route_order_index cannot be null');
        }
        $this->container['route_order_index'] = $route_order_index;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


