<?php
/**
 * QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverageTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Evermile Commercial Quotes and Booking API
 *
 * This is Evermile's commercial API for handling delivery quotes and orders
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@evermile.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverageTest Class Doc Comment
 *
 * @category    Class
 * @description Specific liability coverage info for this proposal
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "QuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverage"
     */
    public function testQuotePost200ResponseDateProposalsInnerProposalsInnerProposalSpecificLiabilityCoverage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_free_liability_cents"
     */
    public function testPropertyMaxFreeLiabilityCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_liability_cents"
     */
    public function testPropertyMaxLiabilityCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liability_coverage_price_per100_cents"
     */
    public function testPropertyLiabilityCoveragePricePer100Cents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
